# Generated by Django 3.2 on 2021-06-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='BookTrending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinfo')),
            ],
            options={
                'db_table': 'booktrending',
            },
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
        migrations.CreateModel(
            name='BookFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinfo')),
            ],
            options={
                'db_table': 'bookfavourite',
            },
        ),
        migrations.CreateModel(
            name='BookDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinfo')),
            ],
            options={
                'db_table': 'bookdiscount',
            },
        ),
    ]
